### ISSUE TITLE
IOBWS 3.0 > Tags need normalization and cleanup

### ISSUE THREAD

**Issue by kristinnstefansson** [stadlar/IST-FUT-FMTH#102]
The schemas e.g. inherited the 'Common Service' tag from the Berlin Group Schema, something with limited usability when using the contract as a whole as clients commonly would. Tags on other endpoints are inconsistent, might at least benefit from being more descriptive.

**Comment by stadlar** [comment]
Þessi lokun er gerð fyrir mistök.
