### ISSUE TITLE
AlterClaim klemma - tilllaga að úrlausn

### ISSUE THREAD

**Issue by stadlar** [stadlar/IST-FUT-FMTH#103]
Varðandi  AlterClaim klemmuna sem við erum í, þá er hugsanlega málamiðlun að gera eftirfarandi:
 
1.	Nota PUT fyrir heildar uppfærslu eins og AlterClaim gerir í dag.
2.	Nota PATCH fyrir skilgreindar breytingar eins og 
a.	TRANSFER
b.	RECREATE
c.	FinalDuedate
d.	Vextir af/á
Þ.e. fast ákveðnar breytingar skv. IOBS staðlinum, Bankarnir geta svo ákveðið sjálfir ef þeir vilja bjóða upp á fleiri möguleika í PATCH.
 
Tillaga frá Sigurður Gauti

**Comment by gudmundurjon** [comment]
Alter claim verður útfært í gegnum batch og PATCH aðgerir.
