### ISSUE TITLE
Notenda kröfur

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#108]
Óskir um breytingar út frá 2013 staðlinum (Grunnurinn er 2013 staðallinn).
Recreate og sundurliðun á claimstatus og claimstate, frumauðkenni og milliinnheimtuauðkenni.

1. Recreate á kröfum í primary og secondary collection
2. Skoðunaraðgangur á auðkennum (claimTemplates) viðskiptavinar og notanda
2.1. Fruminnheimtuaðgangur – aðgangur að fruminnheimtu auðkennum.
2.2. Milliinnheimtuaðgangur – aðgangur að milliinnheimtu aukennum.
2.3. Listi af auðkennum með helstu svæðum skv. lýsingu Guðmundar Jóns á Lista fyrir TemplateCode
2.4. Auk þess væri hægt að sækja sérstaklega detail á ráðstöfun auðkennis (Ráðstöfunnarreikningar og aukaráðstöfun).
3. Hægt verði að frysta kröfu gagnvart greiðslu (IsPaymentAllowed) sb. löginnheimtuauðkennishegðun.
3.1. Krafa hafi IsPaymentAllowed líkt og IsPartialPaymentAllowed, virkar þannig að greiðandinn sér kröfuna en getur ekki greitt kröfuna. Nýtist við löginnheimtu og samkomulög þar sem mikilvægt er að greiðandinn geti ekki borgað ranga fjárhæð. (vísað til VH7)
4. Fyrirspurn krafna bjóði upp á leit skv. breytingardagsetningu frumupplýsinga kröfu
4.1. Í dag er hægt að leita eftir tímabili: skráning, gjalddagi, eindagi og sjálfgefin niðurfellingardag.
4.1.1. Bæta þarf við dags breytt í þann möguleika (LastModifiedDate). Last modified data þýðir, síðasta alter breyting sem hefur verið gerð.
4.1.2. Þegar fyrirspurn er gerð á niðurfellingardag þá er notast við niðurfellingardagsetningu eða raun niðurfellingadag ef krafan sé felld niður.
5. Hægt verði að breyta hluta af kröfu með einfaldari hætti, sérstaklega eftirfarandi
5.1 Höfuðstóll og kostnaðarliðir
5.2. Eindagi
5.3. Vextir af/á
5.4. Leyfa innborgun af/á
6. Hægt að sjá raun stöðu (Innan dags) á kröfu, sb. hefur krafan verið greidd þó/þrátt fyrir að greiðsla hafi ekki verið bókuð.
7. Er ekki hægt að breyta vaxtareglufyrirkomulagi eins og það er í RB í dag.
7.1. Dæmi: Hætta að nota 0-F eins og í dag (2005/2013) en nota í staðinn boolean hvort eigi að reikna dráttavexti, velja síðan dagareglu, síðan er viðmiðunardagur (eindagi,gjalddagi) og síðan er má greiða næsta bankadag.
8. Bætum við á Claim payments (PaymentInfo)
8.1. (*) IsCapitalGainTaxWithdrawn, segir til um hvort búið sé að draga fjármagnstekjuskatt af

**Comment by asgeirh** [comment]
Reminder fyrir næsta fund með notendum:
Mig langar að spurja afhverju payorStatementExtendedReferenceType og customerNumberTemplate var tekið út úr claimTemplate query.  Væri gaman að geta validatað gögn áður en Create er kallað.

**Comment by gudmundurjon** [comment]
ATH, bætt við lið 8 í lýsingu hérna að ofan.

**Comment by gudmundurjon** [comment]
payorStatementExtendedReferenceType -> Ekki lengur leyfilegt og á ekki að vera sýnilegt.
customerNumberTemplate -> Validation fyrir viðskiptanúmer, ekki allir bankar að nota og þar af leiðandi ekki stutt.

**Comment by gudmundurjon** [comment]
1. Recreate á kröfum í primary og secondary collection -> **Notum Alter claim(s)**
2. Skoðunaraðgangur á auðkennum (claimTemplates) viðskiptavinar og notanda -> **Stutt með /v1/claimtemplates og /v1/claimtemplates/{claimTemplateId}**
2.1. Fruminnheimtuaðgangur – aðgangur að fruminnheimtu auðkennum. -> **Aðgengilegt fyrir fruminnheimtuaðila**
2.2. Milliinnheimtuaðgangur – aðgangur að milliinnheimtu aukennum. -> **Aðgangur fyrir bæði frum og milliinnheimtuaðila**
2.4. Auk þess væri hægt að sækja sérstaklega detail á ráðstöfun auðkennis (Ráðstöfunnarreikningar og aukaráðstöfun). -> **Stutt sjá claimTemplateDetails**
3. Hægt verði að frysta kröfu gagnvart greiðslu (IsPaymentAllowed) sb. löginnheimtuauðkennishegðun. -> **Ekki hægt að styðja að svo stöddu máli.**
4. Fyrirspurn krafna bjóði upp á leit skv. breytingardagsetningu frumupplýsinga kröfu -> **claimDetails er með attribute lastChangeDateTime, bæta við í leitina**
4.1.2. Þegar fyrirspurn er gerð á niðurfellingardag þá er notast við niðurfellingardagsetningu eða raun niðurfellingadag ef krafan sé felld niður. -> **Bæta við mögulega í leitarskilyrði niðurfellingardagsetning**
5. Hægt verði að breyta hluta af kröfu með einfaldari hætti, sérstaklega eftirfarandi -> **PATCH verður mögulega niðurstaðan**
6. Hægt að sjá raun stöðu (Innan dags) á kröfu, sb. hefur krafan verið greidd þó/þrátt fyrir að greiðsla hafi ekki verið bókuð. -> **Stutt**
7. Er ekki hægt að breyta vaxtareglufyrirkomulagi eins og það er í RB í dag. -> **Verður ekki breytt frá núverandi stöðu**
8. Bætum við á Claim payments (PaymentInfo) -> **Bankarnir hafa ekki möguleika á að skila þessum gögnum**
8.1. (*) IsCapitalGainTaxWithdrawn, segir til um hvort búið sé að draga fjármagnstekjuskatt af

**Comment by asgeirh** [comment]
1) er ekki hægt að gera einhvað svo að það sé ekki verið að recreate claims óvart með alter?  Það eru oft meira en einn aðili að breyta kröfum og ekki neitt verra en að virkja kröfur óvart.

**Comment by asgeirh** [comment]
> payorStatementExtendedReferenceType -> Ekki lengur leyfilegt og á ekki að vera sýnilegt. customerNumberTemplate -> Validation fyrir viðskiptanúmer, ekki allir bankar að nota og þar af leiðandi ekki stutt.

Afhverju skiptir það máli hvort allir bankar noti þetta eða ekki?  Hvernig væri bara að hafa þetta fyrir þá sem styðja þetta.  Þetta er einhvað sem stoppar stofnun krafna/breytingu hjá þeim bönkum sem nota þetta.

**Comment by siggauti** [comment]
1. Recreate á kröfum í primary og secondary collection -> Notum **Alter claim**(s)
Hvernig væri það útfært í AlterClaim, skiptir verulegu máli.

**Comment by siggauti** [comment]
8. Bætum við á Claim payments (PaymentInfo) -> **Bankarnir hafa ekki möguleika á að skila þessum gögnum**
Kemur á óvart að bankarnir eigi ekki möguleika á að skila þessu.  Skv. lýsingu RB þá er þetta hluti af því sem RB skilar með greiðslu.

![image](https://user-images.githubusercontent.com/64969021/144302247-1a6075c0-1374-4b28-871d-8c06be6802e7.png)

**Comment by siggauti** [comment]
4.1.2. Þegar fyrirspurn er gerð á niðurfellingardag þá er notast við niðurfellingardagsetningu eða raun niðurfellingadag ef krafan sé felld niður. -> **Bæta við mögulega í leitarskilyrði niðurfellingardagsetning**
Það skiptir meira máli er að bæta við möguleika að leita að raun niðurfellingardegi eða daginn sem krafa var felld niður.

**Comment by gudmundurjon** [comment]
Til útskýringar:

4.1.2 -> Hægt væri að leita eftir dagsetningarbili eftir
    Date type
     - "DueDate"
     - "FinalDueDate"
     - "CancellationDate"
     - "CreationDate"
     - "LastChangedDate"
     Status       
     - "Unpaid"
     - "Paid"
     - "Cancelled"
     - "Invalid"
     Collection
     - "PrimaryCollection"
     - "SecondaryCollection"
     - "LegalCollection"

8. Bætum við á Claim payments (PaymentInfo) 
8.1. (*) IsCapitalGainTaxWithdrawn, segir til um hvort búið sé að draga fjármagnstekjuskatt af

**Bankarnir hafa ekki möguleika á að skila IsCapitalGainTaxWithdrawn. En munu skila PaymentInfo**

**Comment by gudmundurjon** [comment]
Breyting á -> Date Type:
- "DueDate"
- "FinalDueDate"
- "CancellationDate" (Hvenær á að fella kröfu niður)
**- "CancelledDate" (Hvenær krafa var felld niður) *NÝTT**
- "CreationDate"
- "LastChangedDate"

Endurnefna 
- "CancellationDate" í "ExpirationDate"

**Comment by gudnithor** [comment]
> "CancellationDate" í "ExpirationDate"

Þetta heitir `CancellationDate` hjá RB. Ætluðum við ekki að reyna að halda okkur við RB orðabókina sem mest?

**Comment by asgeirh** [comment]
> > "CancellationDate" í "ExpirationDate"
> 
> Þetta heitir `CancellationDate` hjá RB. Ætluðum við ekki að reyna að halda okkur við RB orðabókina sem mest?

Mér finnst ekki rétt að halda áfram með villandi lýsingar þótt að upstream provider er með það.  Það þarf allavega skýr mörk á milli það sem á eftir að fella niður og það sem búið er að fella niður.

T.d. 
ExpirationDate og CancelledDate
CancellationDate og RemovedDate

Or something.  CancellationDate og CancelledDate er of villandi

**Comment by asgeirh** [comment]
> > payorStatementExtendedReferenceType -> Ekki lengur leyfilegt og á ekki að vera sýnilegt. customerNumberTemplate -> Validation fyrir viðskiptanúmer, ekki allir bankar að nota og þar af leiðandi ekki stutt.
> 
> Afhverju skiptir það máli hvort allir bankar noti þetta eða ekki? Hvernig væri bara að hafa þetta fyrir þá sem styðja þetta. Þetta er einhvað sem stoppar stofnun krafna/breytingu hjá þeim bönkum sem nota þetta.

@gudmundurjon customerNumberTemplate má ekki bæta því við?  Það er mikilvægt að vita hvort það er regla á þessu eða ekki.  Bankinn sem er ekki með support við þessu getur bara slept þessu field.  Eða bæta við í enum NotImplemented
