### ISSUE TITLE
Claims - LegalCollection - discussion about functionality

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#109]
Úr notendahandbók RB:

>**8.5      KRÖFUR HJÁ LÖGFRÆÐINGI**
>Hægt er að merkja kröfur sem komnar eru í lögfræðiinnheimtu.
>Það er gert með því að stofna kröfuhafann á Kröfuhafaskrá með auðkenni LHx þar sem x getur verið tölustafur eða bókstafur.
>Senda þarf inn í Kröfupott breytingu á kröfunni (auðkenni LHx), eða fella hana niður og stofna nýja með auðkenni LHx.
>Meðan krafan er merkt LHx er ekki hægt að greiða hana.

Samkvæmt RB er þessi kafli úreltur og mun vera breytt. Við vorum að skoða þetta eitthvað árið 2016 en þetta náði engri upptöku hjá okkur. Við eigum ekkert sniðmát í `LHx` í notkun í dag.

Í RB eru þessar `CollectionStatus` til fyrir kröfur:
```
CollectionStatus (Required type at:CollectionStatus [xs:string]) - Staða í innheimtuferli.
        [PrimaryCollection] - Innheimtukrafa hefur verið sett í fruminnheimtu.
        [SecondaryCollection] - Innheimtukrafa hefur verið sett í milliinnheimtu.
        [LegalCollection] - Innheimtukrafa hefur verið sett í lögfræðiinnheimtu.
```
Og fyrir kröfusniðmát:
```
CollectionType (Optional type at:ClaimTemplateCollectionType [xs:string]) - Tegund innheimtu. Segir til um á hvaða innheimtustigi kröfur viðkomandi sniðmáts eru.
        [PrimaryCollection] - Sniðmát fyrir kröfur í fruminnheimtu.
        [SecondaryCollection] - Sniðmát fyrir kröfur í milliinnheimtu.
        [LegalCollection] - Sniðmát fyrir kröfur í lögfræðiinnheimtu.
```

Til þess að setja kröfu í millinnheimtu er notað `ClaimManagement.AlterClaimSecondaryCollection` og til að setja kröfu í löginnheimtu er notað `ClaimManagement.AlterClaimLegalCollection`.

Það sem gerist við að kalla á `ClaimManagement.AlterClaimLegalCollection` er:

1. Krafan er felld niður.
    1. Greiðandi sér ekki kröfuna lengur.
    2. Ekki er hægt að greiða niðurfelldar kröfur (eðlilega).
2. Krafan er hengd á sniðmátið `LH1`.
    1. `LH1` verður hinsvegar ekki til sem alvöru sniðmát á kröfuhafanum.
3. Krafan fær merkinguna `LegalCollection`.
4. Ef krafan er endurvakin þá fer hún aftur í fyrra sniðmát sitt.

-- 

Til umræðu:

Aðrir bankar: Eru þið með `LHx` sniðmát í notkun?

Byggt á þessu hér að ofan leggjum við til:

* Verðum ekki með stöðurnar `LegalCollection` á sniðmátum því það verða aldrei til `LegalCollection` sniðmát.
* Verðum ekki með stöðuna `LegalCollection` á kröfu.
   * Þegar krafan kemst í stöðuna `LegalCollection` þá er hún niðurfelld og engin leið að taka þá merkingu af nema að endurvekja/niðurfella hana.
   * Það er eðlislega mjög lítill munur á því hvort að krafan sé niðurfelld eða sett í `LegalCollection` .

Okkar vegna má þetta samt vera áfram inni en við sjáum ekki alveg notkunargildið og þykjum ekki líklegt að þetta muni ná einhverri notkun. Þetta er í bæði IOBS1 og IOBS2 en ég sé að hjá okkur fá notendur ekkert ef þeir gera `QueryClaims` í stöðunni `LegalCollection` .

**Comment by gudmundurjon** [comment]
Transfer claims styður LegalCollection.

**Comment by asgeirh** [comment]
Þetta er ekki alveg rökrétt. Krafa sem er í merkt löginnheimtu er sjáanleg fyrir greiðanda og hægt að fella hana niður.

Afhverju á þá ekki að leyfa kröfuhöfum að sjá það?  Eiga kröfuhafa bara að sjá stöðuna niðurfellda í Query en samt er hægt að fella hana niður.
