### ISSUE TITLE
Review batch operations

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#110]
Review the following batch operatons
1. claimsRecreationBatch -> (Will be renamed) claimsRecreateBatch
2. claimsCreationBatch
3. claimsCancellationBatch
4. claimsAlterationBatch
5. claimsTransferBatch

**Comment by gummiolafs** [comment]
Teljum þetta vera sama mál og #85, skijlum ekki afhverju þetta eru orðin tvö mál.

Leggjum til að objectin sem batch aðgerðirnar taki og skili líti svona út:

POST INPUT
```
{
	operations: [
		{
			createClaim/alterClaim/deleteClaim: {
				// Same object as the single-operation accepts
			},
		},
		[...]
	]
}
```

POST OUTPUT
```
{
	batchId: "d179e9d8-e4d1-43ae-9ec9-aaa2fc8ae518",
	operations: [
		{
			createClaim/alterClaim/deleteClaim: {
				// Same object as the single-operation accepts
			}
		},
		[...]
	],
	success: 0,
	error: 0,
	pending: 400
}
```

GET INPUT
- batchId from path: `"d179e9d8-e4d1-43ae-9ec9-aaa2fc8ae518"`

GET OUTPUT
```
{
	batchId: "d179e9d8-e4d1-43ae-9ec9-aaa2fc8ae518",
	operations: [
		{
			createClaim/alterClaim/deleteClaim: {
				// Same object as the single-operation accepts
			},
			statusCode: // same as single operation would return AND Null means pending,
			errors: {
				// Error in same format as the single-operation would return if any errors
			}
		},
		[...]
	],
	success: 100,
	error: 100,
	pending: 200
}
```

**Comment by gummiolafs** [comment]
Gerði smá uppfærslu á tillögunni, sjá breytingasöguna

**Comment by gudmundurjon** [comment]
Breyta
POST    /v1/claimbatches -> Stofna bunka af one-of [creation, restoration, cancellation, alteration]
GET      /v1/claimbatches/{batchId} -> Sækja bunka frá fyrri aðgerðium
   Skilagildi úr GET skilar framkvæmdarstöðu per stak í lista

Liður "claimsTransferBatch" er í annari umræðu.

**Comment by gudmundurjon** [comment]
Við viljum ekki blanda saman stökum í innsendum lista.

**Comment by gummiolafs** [comment]
Tillagan frá mér hérna fyrir ofan virðist ekki hafa verið jafn skýr og ég hélt hún væri miðað við umræðurnar á fundinum áðan, þannig ég setti þetta upp í yaml skjali sem ég vonast til að skýri hugmyndina betur. Stillti þessu líka upp út frá því að það yrði bara ein batch aðgerð en ekki sér aðgerð per ekki-batch aðgerð eins og var tillagan fyrir fundinn.

Sjá: https://app.swaggerhub.com/apis/gumol/ClaimBatchProposal

Ferlið hjá notandanum væri þá einhvernveginn svona:

**1. Búa til bunka**
POST á /v1/batches
Request:
```json
{
  "actionType": "claimPost",
  "actions": [
    {
      "body":  
      { 
        /*  Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu */ 
      }
    },
    /* plús 99 kröfur í viðbót */
  ]
}
```
Response:
```json
{
  "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
  "actionType": "claimPost",
  "actions": [
    {
      "body":  
      { 
        /*  Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu */ 
      }
    },
    /* plús 99 kröfur í viðbót */
  ],
  "success": 0,
  "failed": 0,
  "pending": 100
}
```

**2. Sækja stöðu bunka**
Gera GET á /v1/batches/{batchId} til að athuga stöðu
Response:
```json
{
  "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
  "actionType": "claimPost",
  "success": 58,
  "failed": 3,
  "pending": 39
}
```

**3. Sækja ítarupplýsingar bunka**
Sækja stöðu með ítarupplýsingum um hverja kröfu með  GET á /v1/batches/{batchId}?includeActions
Response:
```json
{
  "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
  "actionType": "claimPost",
  "actions": [
    {
      "body":  
      { 
        /*  Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu */ 
      },
      "statusCode": 400,
      "error":  
      { 
        /*  Eins object og POST /v1/claims myndi skila þegar verið er að stofna eina kröfu  */  
      }
    },
    /*  plús 99 kröfur í viðbót */
  ],
  "success": 95,
  "failed": 5
}
```

**Comment by gudmundurjon** [comment]
Mjög skýrt.
Það er líka hægt að nota oneOf í staðinn fyrir "actionType" sjá dæmi https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

**Comment by atliarion** [comment]
Tillaga Arion:

POST /v1/claimbatches/
```
{
  "actionType": "claimPost",
  "claims": [
    {
      "claim":  
      { 
        /*  Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu */ 
      }
    },
    /* plús 99 kröfur í viðbót */
  ]
}
```
Response :
```
{
  "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
  "actionType": "claimPost"
}
```

GET  /v1/claimbatches/{batchid}/Status  -- Eingöngu samantekt
 ```
{
  "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
  "actionType": "claimPost",
  "success": 0,
  "failed": 0,
  "pending": 39,
  "batchstatus": Pending, InProgress, Completed, CompletedWithErrors
}

```

-- Eftirfarandi aðgerðir skila þá lista af kröfum og hvernig gekk að stofna
GET  /v1/claimbatches/{batchid}  -- Sama og ?includeActions=All
GET  /v1/claimbatches/{batchId}?includeActions=Success  -- Geta sótt eingöngu þær sem tókst að stofna
GET  /v1/claimbatches/{batchId}?includeActions=Error    -- Geta sótt eingöngu þær sem ekki gekk að stofna
aka:
```
{
  "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
  "actionType": "claimPost",
  "claims": [
    {
      "claim":  
      { 
        /*  Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu */ 
      },
      "statusCode": 400,
      "error":  
      { 
        /*  Eins object og POST /v1/claims myndi skila þegar verið er að stofna eina kröfu  */  
      }
    },
    /*  plús 99 kröfur í viðbót */
  ],
  "success": 95,
  "failed": 5,
  "pending": 0, 
  "batchstatus": CompletedWithErrors  
}
```

**Comment by gudmundurjon** [comment]
Tillaga frá Landsbanka samþykkt með breytingu á svari við skráningu bunka, svarið verður:
Response :
{
  "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
  "actionType": "claimPost",
  "success": 139,
  "failed": 0,
  "pending": 0
}

**Comment by gudmundurjon** [comment]
Breytum includeAction úr einum query param sub resource
- ../success
- ../failed

**Comment by asgeirh** [comment]
er ekki hægt að includa claim keys á failed? og villuskilaboð?

**Comment by asgeirh** [comment]
Ég er því miður ekki að skilja afhvejru er verið að gera þetta svona.

Eftir að búinn er til bunki þá þarf ég að kalla í GET /v1/claimbatches/{batchId} þangað til bunkinn er búinn að keyra SVO
Þarf ég að sækja GET /v1/claimbatches/{batchId}/success til að vita hvað var successful og fá ALLT claim object til baka for some reason.  Svo þarf að kalla á GET /v1/claimbatches/{batchId}/failed til þess að fá að vita hvað klikkaði.  Svo til að toppa allt þá eru þessir listar paged en hægt að posta öllu.

Afhverju fáum við ekki bara failed return objectið frá GET /v1/claimbatches/{batchId}.   Ég veit nú þegar hvað ég sendi margar kröfur inn ég þarf ekki talningu til baka.  EN ég þarf að vita hvaða kröfur voru stofnaðar í beingreiðslu og hvaða kröfur var ekki hægt að stofna / breyta / fella niður.

**Comment by gudmundurjon** [comment]
Til að brjóta niður það sem @asgeirh nefnir.
1. Þrjár aðgerðir POST, GET x 2 til að sjá hvað var gert
2. Paging, spurning hvert hámarkið er hjá bönkunum
3. Hvaða kröfur eru í beingreiðslur

Leggjum til að breyta svari:
{
    "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
    "actionType": "claimPost",
    "success": 1,
    "failed": 1,
    "pending": 0,
    "actions": [{
      "body":  {  /*  Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu */   },
      "statusCode": 400, /* Http status code */
      "response":  {   /*  Eins object og POST /v1/claims myndi skila þegar verið er að stofna eina kröfu  */  }
    }],
}
-og- 
bæta við query param "includeActions" sem segir til um hvort "actions" svæðinu er skilað.

Með þessu móti verður ein aðgerð til að framkvæma þar sem svarinu væri skilað strax án þess að þurfa að gera fleiri aðgerðir.

**Arion banki og Íslandsbanki ætla að staðfesta þessa mögulegu virkni áður en við gerum þessar breytingar.**

**Comment by atliarion** [comment]
Eftir að hafa rætt þetta og skoðað hvað RB interface býður upp á í dag komumst við að eftirfarandi niðurstöðu.
Stofna er með POST:
> ```
>POST á /v1/batches
>
> {
>   "actionType": "claimPost",
>   "actions": [
>     {
>       "body":  
>       { 
>         /*  Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu */ 
>       }
>     },
>     /* plús 9 kröfur í viðbót */
>   ]
> }
> ```

Miðað við interface hjá RB í dag munum við svara svona þangað til öll item eru  komin úr pending yfir í Success eða Failed:

> ```
> GET á /v1/batches/{batchid]
> 
> {
> "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
> "actionType": "claimPost",
> "success": 0,
> "failed": 0,
> "pending": 10
> }
> ```
> 

Þegar við fáum frá RB að búið er að vinna úr öllum geturðu fengið body hlutann með og result af því:

> ```
> GET á /v1/batches/{batchid]
> 
> {
> "batchId": "288558fb-a463-4814-b88e-ee014be55e6c",
> "actionType": "claimPost",
> "success": 7,
> "failed": 3,
> "pending": 0,
> "actions": [{
> "body": { /* Eins object og er tekið við í POST /v1/claims þegar verið er að stofna eina kröfu / },
> "statusCode": 400, / Http status code /
> "response": { / Eins object og POST /v1/claims myndi skila þegar verið er að stofna eina kröfu */ }
> }],
> }
> ```

Spurning hvort einhver þörf er á includeActions param. Hann má vera, en meðan allt er í pending er ekki neitt body að skila.
Við setjum þó spurningu við að það á eftir að tækla hvernig raunverulegum villum sem koma upp við stofnun á stakri kröfu er komið til skila til endanotanda. Hentar http error fyrir allt sem upp getur komið við stofnun á kröfu.
