### ISSUE TITLE
Berlin Group útgáfa

### ISSUE THREAD

**Issue by stadlar** [stadlar/IST-FUT-FMTH#116]
•	GJH leggur til að taka upp nýjustu útgáfu Berlin Group 
•	KS leggur til að byrjað verði á að samræma útgáfuröðina af skjölunum, þannig að hægt sé að rekja söguna línulega. Í framhaldi verði breytingasagan með vísun í Berlin group skýrð.   
•	Rita pull request á málið. 
1.	Knöpp lýsing þarf að setja í titil á pullrequest 
•	Samræma IOBWS3.0 í nýjustu útgáfu - 1.3.8 frá 1.3.5 
2.	Forsendur fyrir breytingunni. 
•	Athuga uppfærslu 
3.	Hvers vegna var útfærslan valin 
•	Fylgja útgáfum BG eins og hægt er -eða taka meðvitaða ákvörðun um að gera það ekki. 
4.	Hver eru þekkt áhrif breytingarinnar 
•	Óþekkt - GJH  
i.	Errata sem fylgir breytingunni milli útgáfa 
5.	Hvernig á að prófa breytinguna 
•	Ekki hægt - eða kemur í ljós, er skilgreiningar, prófa syntax 
6.	Stutt samantekt þarf að skrá í release.md 
•	Verður tekið sama þegar pull requestið er unnið 
•	Verklag stendur – þegar farið verður í þessa uppfærslu. 
•	KS - uppfæra vísun í Berlin group staðal og uppfæra ekki þetta skjal fyrr en komin er útgáfan IOBWS3.1. 
•	Ákveðið að fara hægar í uppfærslur en áður var fyrirhugað, stefnt að uppfærslu í nýjustu útgáfu Berlin Group tæknistaðalsins vor 2022. 
•	 Verkefnið í bið – nema fram komi pull request.

**Comment by kristinnstefansson** [comment]
In meeting 24.11.2021 the need for upgrade was discussed, at this moment there is not a driving need identified so this was closed for now.
