### ISSUE TITLE
X-Request-ID strategy

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#118]

**Comment by gummiolafs** [comment]
Sjá umræður í máli #99

Eins og fram hefur komið er X-Request-ID header notaður víða án þess að idempotency virkni sé á bakvið hann. Þetta er ekki staðlaður header eins og X- forskeytið ber með sér þannig útfærslur geta verið á alla vegu og engin þeirra er réttari en önnur. Algengasta notkunin sem við vitum um er fyrir loggun þannig hægt sé að rekja kall í gegnum mögulega langa keðju frá tæki notanda innst inn í bakendakerfi með einkvæmu auðkenni.

Við leggjum til að þetta auðkenni kallsins verði eingöngu notað í þessum tilgangi og hafi ekki önnur hliðaráhrif. Það er á ábyrgð þess sem kallar að hafa þetta gildi einkvæmt og það á ekki að valda villu þjónustu megin ef svo er ekki.

**Comment by kristinnstefansson** [comment]
@gudmundurjon : Add references to code changes and close issues.

**Comment by gudmundurjon** [comment]
X-Request-ID er notað í fyrirspurn og skilað með svari. 
Idempotency virkni er nú þegar komin inn.
