### ISSUE TITLE
IOBWS 3.0 > Documents

### ISSUE THREAD

**Issue by kristinnstefansson** [stadlar/IST-FUT-FMTH#121]
The IOBWS-Documents3.0.yaml does not pass validation in the state it was accepted, and could not be used as a basis for an implementation. It does not seem to be fully in alignment with the documentation and examples are missing from the YAML. A suggestion for fix will be forthcoming in a Pull Request, as well as consolidation with cards and currencies. 
The idempotency issue for documents need to be faced, and merged into the contract.

**Comment by gudmundurjon** [comment]
My mistake, I had the fix stashed. Will push now.

**Comment by kristinnstefansson** [comment]
@gudmundurjon + @stadlar : This should absolutely have been submitted as a PR, given that the Technical Specification has already been published. Not the least as the document still contains syntax errors that, while not as critical as the previous errors, will prevent consumption by some tools. I would strongly suggest holding off further changes on main without PR discussed as part of VH-7 work or 'verkþáttur-5'.
