### ISSUE TITLE
IsPaymentAllowed 

### ISSUE THREAD

**Issue by stadlar** [stadlar/IST-FUT-FMTH#132]
Þessi punktur er úr Issue #108  Notendakröfur og GV var á TN-FMÞ-VH 66 falið að koma honum á dagskrá VH7.

Hægt verði að frysta kröfu gagnvart greiðslu (IsPaymentAllowed) sb. löginnheimtuauðkennishegðun.
3.1. Krafa hafi IsPaymentAllowed líkt og IsPartialPaymentAllowed, virkar þannig að greiðandinn sér kröfuna en getur ekki greitt kröfuna. Nýtist við löginnheimtu og samkomulög þar sem mikilvægt er að greiðandinn geti ekki borgað ranga fjárhæð.

**Comment by kristinnstefansson** [comment]
Needs to be discussed in the appropriate "Framtíðarhópur" in RB, as this affects product development.
