### ISSUE TITLE
Athugasemdir og breytingar vegna á kröfu yaml skjals

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#135]
1. Taka öll documentreference út
2. Nota Json Merge patch
3. Í staðinn fyrir specialCode, setja inn nýja RB skilgreininguna
4. Bæta við ClosingDate á kröfufyrirspurn og skjala skv. RB
    - ClosingDate (Optional type xs:dateTime) - Dagsetning þegar krafa var greidd, niðurfelld eða flutt.
5. Bæta við í collectionState stöðunni WaitingForSecondary og skjala
6. Bæta við claimTemplateId query parameter fyrir get claims og transactions og i svarskeitinu
7. Endurnefna "percentage4" í "percentage", setja í lýsingu að aðeins sé 4 aukastafir
8. Endurnefna "rateValue" í "percentageValue" og laga lýsingu, % er af hundraði.
9. Taka út  /v1/claims/{claimId} delete þar sem hún er bæði í patch og batch
10. Má taka út recreate og cancel í batch þar sem alter getur bæði endurvakið og hætt við kröfur
11. Þegar krafa er stofnuð kemur þar að skila hvort krafan sé í beingreiðslu eða ekki. (Beingreiðsla = DirectPaymentClaim)
12. Þegar word skjalið er ritað verður yaml ekki sett í skjalið. Öll dæmi (en. Examples) verða sett í yaml-ið í staðinn.

**Comment by gudmundurjon** [comment]
Laga texta "Returns all claim payments. When claim is paid by debtor the claim paymentis visible is near real-time."

**Comment by asgeirh** [comment]
1. Geta bankarnir staðfest þetta.  Það er mjög líklegt að ef þetta fer í breytingarnefnd þá mun þetta ekki vera notað.  Ef þetta er vinna sem RB er nánast búin með.

**Comment by gudmundurjon** [comment]
> 1. Geta bankarnir staðfest þetta.  Það er mjög líklegt að ef þetta fer í breytingarnefnd þá mun þetta ekki vera notað.  Ef þetta er vinna sem RB er nánast búin með.

Guðmundur  Valsson sendir á breytingarhópinn

**Comment by asgeirh** [comment]
> > 1. Geta bankarnir staðfest þetta.  Það er mjög líklegt að ef þetta fer í breytingarnefnd þá mun þetta ekki vera notað.  Ef þetta er vinna sem RB er nánast búin með.
> 
> Guðmundur Valsson sendir á breytingarhópinn

Sæll Guðmundur,  Þetta er smá misskilningur,  Ég var að byðja um að þessi breyting verði ekki send í breytinganefnd heldur haldið inni í núverandi yaml þar sem RB er að klára þessa breytingu. 

Ég er mjög hræddur um að eftir að þetta kemur úr breytinganefn þá implementi bara 1 eða 2 bankar þessa breytingu og þá get ég ekki notað hana þar sem allir bankar eru ekki með support fyrir þetta.  Það þarf bæði að setja reference á skjal í stofnun og svo þurfa allir bankar að vera að sýna þessi skjöl í ógreiddum kröfum.

**Comment by stadlar** [comment]
GET Transactions (Með og án claim) vantar:
                              RedeemingBank
                              CategoryCode
                              Reference
                              BillNumber
                              CustomerNumber
                              BatchNumber
                              TemplateCode
                              SecondaryCollectionTemplateCode
                              Legal?
                                            
                              Það vantar upphæðið (Mjög important!)
                                             TotalAmountDue
                                             NoticeChargeAmount
                              DefaultChargeAmount
                              OtherCostsAmount
                              OtherDefaultCostsAmount
                              DefaultInterestAmount

               

               GET Claims/Claim vantar:
                              SecondaryCollectionTemplateCode
                              Legal?


               Það vantar documentation á hvað þýður isPermitOutOfSequence payment.  Hvernig þarf krafan að vera til að uppfylla þetta requirement?  Sama Account, Reference, Customernumber osf.

               GET /v1/batches/{batchId}
          Svarið ætti að vera sama og failed var (Print ætti að vera eitthvað annað)
{
  "id": "stringstringstringstringstringstring",
  "status": "InProgress",
  "success": [
    {
      "claimKey": {
        "claimantId": "0208715009",
        "accountNo": "000126123456",
        "dueDate": "2022-01-18"
      },
      "print": true
    }
  ],
  "errors": [
    {
      "claimKey": {
        "claimantId": "0208715009",
        "accountNo": "000126123456",
        "dueDate": "2022-01-18"
      },
      "error": {
        "code": "string",
        "message": "string"
      }
    }
  ]
}

**Comment by stadlar** [comment]
Frá Ásgeiri á fundi 67
