### ISSUE TITLE
2022-02-08 Meeting notes

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#140]
## Íslandsbanki -> Athugasemdir og svör

1. get::/v1/claimtemplates (response)
collectionType
Vantar LegalCollection í enum
**Svar**: Senda á viðhaldshópinn

2. get::/v1/claimtemplates (response)
isActive
Ætlaði RB að bæta þessu í getClaimTemplates?
**Svar**: Taka út úr yaml, og senda á viðhaldshópinn

3. get::/v1/claimtemplates (response)
lastModified
Er þetta nýtt svæði? Var ekki bara lastChangedDateTime fyrir kröfu? Er ekki í lista nér detail fyrir template
**Svar**: Taka út úr yaml, og senda á viðhaldshópinn

4. get::/v1/claimtemplates/{claimTemplateId} (response)
collectionType
Vantar LegalCollection í enum
**Svar**: Senda á viðhaldshópinn

5. get::/v1/claimtemplates/{claimTemplateId} (response)
lastModified
Er þetta nýtt svæði? Var ekki bara lastChangedDateTime fyrir kröfu?	
**Svar**: Taka út úr yaml, og senda á viðhaldshópinn

6. get::/v1/claims/{claimId} (response)
claimKey/account
á þetta ekki að vera eitthvað í líkingu við claimId - finnst ruglandi að lýsingin segi "Icelandic Bank Account Number Identifier."	
**Svar**: Laga texta lýsingu

7. get::/v1/claims/{claimId} (response)
defaultInterest
þetta er í engu samræmi við RB - viljum við ekki að þetta sé ca eins ?	
**Svar**: Uppfæra skv. RB

8. get::/v1/claims/{claimId} (response) 
discount / isPostRefDate	vantar
**Svar**: Bætt við og lýsingu

9. get::/v1/claims/{claimId}/transactions (response)
claimId / claimKey
Sömu gögnin
**Svar**: Taka út claimId

10. get::/v1/claims/{claimId}/transactions (response) 
amount
Betri lýsingu - hvaða upphæð er þetta - höfuðstóll kröfu ?
**Svar**: Uppfærð lýsing

11. get::/v1/claims/{claimId}/history (response) 
transactionType
ekki í samræmi við type hjá RB. 
**Svar**: Uppfært skv. Lýsingu

12. get::/v1/claims (response)
claimStatus
Hvað ef krafa er transfered? Getur þessi staða komið upp
**Svar**: Fært á næsta fund

13. get::/v1/claims (response)
referenceRate
Þessar upplýsingar eru ekki í boði í dag ef búið er að greiða kröfuna	
**Svar**: Á ekki við

14. post::/v1/claims (request) 
"expirationDate"
þarf að vera required
**Svar**: Uppfært skv. Lýsingu

15. post::/v1/claims (request) 
currency
Vantar meiri upplýsingar til að geta stillt kröfuna hjá RB
**Svar**: Uppfært skv. Lýsingu

16. post::/v1/claims (request) 
referenceRate
RB er einungis með tvö gildi í sínu enum DueDateRate og PaymentDateRate	
**Svar**: Uppfært skv. Lýsingu

17. patch::/v1/batches
Aðgerðin á að vera Post en ekki Patch	
**Svar**: Post aðgerð verður bætt við

## Notendur
1. Setja í breytingarnefndina: Er hægt að frá einkvæmt númer fyrir claimTransaction og claimHistory færslur

**Comment by asgeirh** [comment]
9.  Það er ekki búið að taka út claimId

**Comment by gudmundurjon** [comment]
Batches:
1. Henda patch
2. Fyrir post verða tveir listar, Create, Alter þar sem alter fylgir merge patch

claimId tekið úr example fyrir claimTransaction.
