### ISSUE TITLE
DefaultInterest - NoDefaultInterest

### ISSUE THREAD

**Issue by siggauti** [stadlar/IST-FUT-FMTH#165]
I have a question,  in DefaultInterest class, how am I able to request NoDefaultInterest?

If I look at the Description: it looks like the NoDefaultInterest is missing in BaseAmountType:
_description: | Contains information on how penalty interest is calculated. **NoDefaultInterest**: No penalty interest shall be required.**DefaultInterestAmount**: Indicates that penalty interest is calculated on the basis of the amount claim. **DefaultInterestAmountAndDefaultCharge**: Indicates whether penalty interest is calculated on the basis of the amount and arrears of the claim. Percentage: (4 decimal, example: 12.1234 ) Indicates the percentage of penalty interest, may not be higher than the Central Bank's maximum permitted penalty interest rate. If the penalty interest rule specifies that penalty interest is to be calculated and this value is not specified, the Central Bank's maximum penalty interest rate is used automatically._

public enum BaseAmountTypeEnum
        {
            /// <summary>
            /// Enum AmountEnum for Amount
            /// </summary>
            [EnumMember(Value = "Amount")]
            **AmountEnum** = 0,
            /// <summary>
            /// Enum AmountAndDefaultChargeEnum for AmountAndDefaultCharge
            /// </summary>
            [EnumMember(Value = "AmountAndDefaultCharge")]
            **AmountAndDefaultChargeEnum** = 1
        }

**Comment by haukurhrafn** [comment]
> Ok, I understand that null would indicate NoDefaultInterest, I wounder how the PATCH of an Claim can determine the difference of NoDefaultInterest or do not change DefaultInterest values? And then the others also Discount and DefaultCost.

I have been wondering the same thing. Here is my conclusion: 
Given the name of the PATCH request is _mergeClaimDetails_ I'm assuming it adheres to the [JSON Merge Patch IETF standard](https://datatracker.ietf.org/doc/html/rfc7396). 

Short answer to your question would then be that if one of the fields in the PATCH request has a null value then that tells the server to delete that field from the claim resource. If the fields are not present in the PATCH request they are not modified.

There is a good example of how to add, change and remove fields in the [RFC 7369](https://datatracker.ietf.org/doc/html/rfc7396).

Hope this helps :)

**Comment by siggauti** [comment]
> > Ok, I understand that null would indicate NoDefaultInterest, I wounder how the PATCH of an Claim can determine the difference of NoDefaultInterest or do not change DefaultInterest values? And then the others also Discount and DefaultCost.
> 
> I have been wondering the same thing. Here is my conclusion: Given the name of the PATCH request is _mergeClaimDetails_ I'm assuming it adheres to the [JSON Merge Patch IETF standard](https://datatracker.ietf.org/doc/html/rfc7396).
> 
> Short answer to your question would then be that if one of the fields in the PATCH request has a null value then that tells the server to delete that field from the claim resource. If the fields are not present in the PATCH request they are not modified.
> 
> There is a good example of how to add, change and remove fields in the [RFC 7369](https://datatracker.ietf.org/doc/html/rfc7396).
> 
> Hope this helps :)

Thanks, can we put this short answer in the api description for clear functionality.

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-18 discussed that an overall description or reference to RFC 7369 on how PATCH requests work should be handled in the Technical Specification and not the API description, as that might require too much context and text.

**Comment by kristinnstefansson** [comment]
This issue was addessed in the 3.1 work done by workgroup VH-7.
