### ISSUE TITLE
Claims - Inconsistency in the type of amount properties?

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#166]
I have a question regarding the types of the amount properties of [**claimDetails**](https://github.com/stadlar/IST-FUT-FMTH/blob/c4ea6b6bc254d7469e61302fed12146dbcbfe0b0/Deliverables/IOBWS-Claims3.0.yaml#L1370).

Most of the properties are defined as _number_. However _otherCosts_, _otherDefaultCosts_ and _dayAmountItem.Value_ (used in defaultCharge and discount) are defined as _integer_. The corresponding properties in IOBWS 2.0 are not integers.

Is there a specific reason for this or should they all be of the type _number_?

**Comment by danielsveins** [comment]
It should be noted that the same goes for the corresponding properties in other objects, such as [**createClaimDetails**](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1592) and [**mergeClaimDetails**](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1512).

**Comment by Kristinn-Stefansson** [comment]
Meeting of TN-FMÞ-VH7-15 discussed that this was probably not due to a concious decision and could generate problems or at least create unecessary work in implementation. The suggestion is therefore that all these fields should be made number across the board.
The next step would be to receive a PR.

**Comment by kristinnstefansson** [comment]
This issue was addessed in the Claims 3.1 work done under workgroup VH-7. See the referenced comments and changes.
