### ISSUE TITLE
Claims - Inconsistency in the type of percentage properties?

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#167]
I have a question regarding the types of the percentage properties of [**claimDetails**](https://github.com/stadlar/IST-FUT-FMTH/blob/c4ea6b6bc254d7469e61302fed12146dbcbfe0b0/Deliverables/IOBWS-Claims3.0.yaml#L1370).

[_percentage_](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1332) in _defaultInerest_ is defined as _number_. 
_defaultCharge_ and _discount_ ([dayAmountItem](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1154)) can be either fixed amount or percentage. They are defined as _integer_.

Is there a specific reason for this or should they all be of the type number?

**Comment by kristinnstefansson** [comment]
This issue was addessed in the Claims 3.1 work done under workgroup VH-7. See the referenced comments and pull requests as appropriate.
