### ISSUE TITLE
Claims - isPermitOutOfSequencePayment

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#168]
The naming of _isPermitOutOfSequencePayment_ (in [**mergeDetails**](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1370)), the property which indicates whether it is allowed to pay the last payment if previous has not been paid, is a bit weird and confusing.

A clearer and more natural name would be _isOutOfSequencePaymentPermitted_. An even better name could be _isOutOfSequencePaymentAllowed_ as it would be consistent with _isPartialPaymentAllowed_ which is another property of _mergeDetails_.

**Comment by Kristinn-Stefansson** [comment]
Meeting of TN-FMÞ-VH7-15 discussed that as Allowed was used and the sequence of word parts in current naming was strange the property should be named _**isOutOfSequencePaymentAllowed**_ as suggested.
The next step would be to receive a PR.

**Comment by Kristinn-Stefansson** [comment]
Approved according to agreement on TN-FMÞ-VH7-18 and PR merged
