### ISSUE TITLE
Claims - Inconsistency in naming of reference date properties

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#170]
There is an inconsistency in the naming of reference date properties in [**claimDetails**](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1370).

In _defaultCharge_, the property is called _referenceDate_. But in _defaultInterest_, it is called _dateReference_. Should be _referenceDate_ in both cases since it's more descriptive.

**Comment by Kristinn-Stefansson** [comment]
Meeting of TN-FMÞ-VH7-15 discussed this suggestion and accepts it without further discussion.
The next step would be to receive a PR.

**Comment by Kristinn-Stefansson** [comment]
Change approved according to agreement on TN-FMÞ-VH7-18 and PR merged
