### ISSUE TITLE
Claims - Format of claimTemplateId

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#172]
The description for _claimTemplateId_ is "Unique template id defined by the banks."

Could _claimTemplateId_ follow a similar similar format as [_claimdId_](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L780) rather than being left ambiguous and up to the implementation of each bank?

For example: bankNumber + claimantId + templateCode. pattern: [0-9A-Z]{17}

**Comment by Kristinn-Stefansson** [comment]
Meeting of TN-FMÞ-VH7-15 determined that there had been an explicit design desicion to have this ID openended and not interoperable or comparable between banks. The _claimTemplateId_ would therefore remain as it is defined currently.
