### ISSUE TITLE
Claims - BatchId in ClaimTransaction

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#173]
[**claimTransaction**](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1773) has the property [_batchId_](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1877). According to the current definition of IOBWS-Claims3.0.yaml this is the Id of the claim batch. The same Id is used in [_/v1/batches/{batchId}_](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L697) for example.

I assume this is supposed to be the Id of the payment batch, as is the case in IOBWS 2.0. If so then it would be ideal to define a new property which indicates that clearly, i.e. _paymentBatchId_.

**Comment by kristinnstefansson** [comment]
The batchID seems to correspond to the older 162:2013 "Bunkanúmer greiðslu", which would be a 4 char indicator that is fast becoming obsolete. Instead a unique payment ID would be a future improvement, when that becomes possible. Having the "redeemingBank" on hand with the BatchID of the Payment can help with tracing issues but is dependant on it being available. 

The suggestion from meeting TN-FMÞ-VH7-16 is to rename "redeemingbank" to transactionBank and BatchId to transactionBatchID. The descriptions might also include further context.

**Comment by Kristinn-Stefansson** [comment]
Approved according to agreement on TN-FMÞ-VH7-18 and PR merged
