### ISSUE TITLE
Claims - claimTransaction property names

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#174]
The purpose of the following properties, in [**claimTransaction**](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1773), might be made clearer with more descriptive names.

- noticeChargeAmount - Description missing
- defaultChargeAmount - Description missing
- otherCostsAmount - Otherwise cost to pay.
- otherDefaultCostsAmount Other default paid.
- defaultInterestAmount - Amount of accrued penalty interest paid.
- discountAmount  - Discount that was granted when a claim was paid.
totalAmount - Total amount paid with accrued interest and fees.

Suggested names and descriptions:

- noticeChargeAmountPaid - Notice charge paid.
- defaultChargeAmountPaid - Default charge paid.
- otherCostsAmountPaid - Other costs paid
- otherDefaultCostsAmountPaid - Other default costs paid.
- defaultInterestAmountPaid - Amount of accrued default interests paid.
- discountAmountGiven - Discount that was granted when a claim was paid.
- totalAmountPaid - Total amount paid with accrued interests and fees.

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-16 discussed aligning the naming in accordance with previous suggested changes and naming in the core IH system. The suggestion was accepted.

**Comment by Kristinn-Stefansson** [comment]
Marked as processed in line with agreement on TN-FMÞ-VH7-18
