### ISSUE TITLE
Claims - Inconsistency between the claim key in RB and IOBWS-Claims3.0

### ISSUE THREAD

**Issue by thebingi** [stadlar/IST-FUT-FMTH#175]
There is an inconsistency between the claim keys in RB and IOBWS-Claims3.0.

The key in RB is composed, for example, like this:

030166547187660612998020230405
Claim number - Kennitala of the claimant - Due date

The key in IOBWS-3 for the same claim is as follows:

660612998003016654718720+230405
Kennitala of the claimant - Claim number - Due date

That is, the Kennitala and claim number are switched. 

Additionally, there is a plus sign before the due date in IOBWS-Claims3.0.
Using a plus sign (+) in a query string for a REST API is possible, but it is not recommended, as it can lead to confusion or incorrect parsing. In URLs, the plus sign is commonly used to represent a space character. When a query string includes a plus sign, it might be interpreted as a space by some systems or libraries, causing unexpected behavior.

I would like to be able to input the IOBWS-3 key into the IH interface at RB to look up a claim. This could save a lot of manual work in the coming years.

When a request was sent to RB to investigate this, it was not well-received, and they referred to the standards committee. See the response below.

> Því miður vitum við hjá RB ekki afhverju loka útgáfa staðalsins gerir ráð fyrir annarri framsetningu á kröfulykli en er í vefþjónustum RB. 
> 
> Þátttaka RB í vinnu staðlaráðsins var fyrst og fremst til að veita upplýsingar um þá möguleika sem til staðar eru í Kröfupottinum og skýra virkni en einnig fórum við yfir öll drög á ákveðnum tímapunkti og gerðum athugsemdir í þeim tilvikukm þar sem t.d. nöfn og annað var frábrugðið vefþjonustum RB.
> VIð þekkjum því miður ekki hvernig var unnið úr þeim athugasemdir eða hvaða ástæður liggja að baka loka framsetningunni.  
> 
> Ég tel að það væri nærtækast fyrir Arion að vekja athygli Staðlaráðs á þessu og óska eftir breytingum ef við á.
> En ég get einnig unnið málið áfram með framþróunarhópnum og vakið athygli hans á þessu og geta þeir þá hlutast til um það að fulltrúar þeirra í Staðlaráði geri athugasemdir við framsetningu staðalsins.
>

**Comment by Kristinn-Stefansson** [comment]
Meeting of TN-FMÞ-VH7-15 discussed the question and suggestion. The overriding factor in the decision when it was made was matching this up with the implementation in the Payment schema. Therefore this will remain unchanged currently.
