### ISSUE TITLE
Claims - Refinement of Payment Properties Terminology: Replacing DirectDebitFee with PaperlessFee

### ISSUE THREAD

**Issue by thebingi** [stadlar/IST-FUT-FMTH#178]
I noticed while examining the GetClaims operation that the wording was peculiar. The payment includes two properties: paymentFeeAmount and directDebitFee. The idea here is that those who are enrolled in direct debit receive, for example, a lower fee than those who receive a payment slip.

NoticeAndPaymentFee has been renamed from the previous standard to PaymentFee. 
DirectDebitFee should map to PaperlessFee at RB, but that is not the correct terminology.

Using the term directDebitFee is not accurate because this field is not related to whether the individual is enrolled in direct debit. The individual may have opted out of paper and thus pays a paperless fee. However, the individual does not necessarily have to be enrolled in direct debit, so it is not related.

I suggest using the same terms as those employed by the RB
NoticeAndPaymentFee, which contains two properties - PrintingFee and PaperlessFee.

**Comment by Kristinn-Stefansson** [comment]
Meeting TN-FMÞ-VH7-16 deliberated and found this change to be acceptable and an improvemtn.

**Comment by asgeirhall** [comment]
When we had this discussion on the meetings we were told that the only way to pay the Paperless fee was having the claim debited directly from your account.

The Paper fee was when you were not enrolled in direct debit.  Because I dont see any option in my bank to "out out of paper".   I assume banks dont send so much paper anymore.

**Comment by thebingi** [comment]
I was not present at the meeting you're referring to. This is merely an additional charge added to the claim, a Paper Fee or a Paperless Fee. The claimant sets these fees, and in some instances, claimants may apply the same fee to both.

When the payor is in Direct Debit, they are categorized as Paperless. However, a payor can also be categorized as Paperless even when not in Direct Debit. Some banks even offer their customers the option to register as paperless. In essence, the term Paperless encompasses a wider scope than Direct Debit.

Here's the corresponding documentation from the claim system:

PrintingFee : This fee is applied if a claim is physically printed out.
PaperlessFee : This fee is applied if a claim is paperless, i.e., it's not printed out, and this is also applicable for claims in direct debit.

**Comment by Kristinn-Stefansson** [comment]
Approved according to agreement on TN-FMÞ-VH7-18 and PR merged
