### ISSUE TITLE
Claims - Payments

### ISSUE THREAD

**Issue by asgeirhall** [stadlar/IST-FUT-FMTH#188]
I was told that the new Sopra payment system would allow the full key of the payment of a claim to be made available in bank account transactions.

Currently today very limited information is added to the transaction and its VERY hard to match payments on accounts with claim payments.  Having the full key DueDate, Claimant registry id, Account number (Bank, Ledger, Number) is needed for proper matching.  Today most often we have last 6 digits of acccount number but very often we have two or three payments with the same amount, number and payor.

**Comment by Kristinn-Stefansson** [comment]
Closed for now

**Comment by asgeirhall** [comment]
Hello @Kristinn-Stefansson it would be nice to know how to match the claim payment in the bank transactions.  Because I have not found a way to match payments for claims that have.

A. Same DueDate and Diffrent Account Number.  Bill number is DueDate
B. Diffrent DueDate and Same account number. Bill number is last 6 digits of Claim account number

**Comment by haukurhrafn** [comment]
I think you have a point @asgeirhall. It's not been easy to match the payments in such cases given the limited fields in the old ibm mainframe. From the information I've been able to gather Sopra solves those limitations and provides full referance to a claim in a transaction that is to be exposed through the [remittanceInformationStructuredArray ](https://github.com/stadlar/IST-FUT-FMTH/blob/c4ea6b6bc254d7469e61302fed12146dbcbfe0b0/Deliverables/IOBWS3.1.yaml#L4904)on transactionDetails in IOBWS 3.0 AIS.

In the cases you mentioned have you tried using the [referance ](https://github.com/stadlar/IST-FUT-FMTH/blob/c4ea6b6bc254d7469e61302fed12146dbcbfe0b0/Deliverables/IOBWS-Claims3.0.yaml#L1442C15-L1442C15)field (Tilvísun) on a Claim to match the payment transaction. If you place a uniqe identifier in the reference field when you create a claim you should see that same uniqe identifer as a referance on the payment transaction.

**Comment by asgeirhall** [comment]
Reference field is always filled with PayorId on bank account when claims are paid.

BillNumber (Max 7 chars) and PayorId (and amount is a indicator) are the only fields that can be used for matching.
