### ISSUE TITLE
 Claims - GetClaim(s) API Response - CreatedDate

### ISSUE THREAD

**Issue by thebingi** [stadlar/IST-FUT-FMTH#189]
When fetching data using the GetClaims API endpoint, it's often useful to have information about when each claim was created. To facilitate this, I propose including a CreatedDate property in the response data.  This is part of the response from RB and easy to implement. 

**RB Documentation**
CommencementDate - Stofndagur kröfu.

**Comment by Kristinn-Stefansson** [comment]
Meeting TN-FMÞ-VH7-16 saw this as an improvement that should be implemented.

**Comment by Kristinn-Stefansson** [comment]
Marked as processed in line with agreement on TN-FMÞ-VH7-18
