### ISSUE TITLE
Claims - Unnecessary properties in default interests

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#195]
The [defaultInterest](https://github.com/stadlar/IST-FUT-FMTH/blob/master/Deliverables/IOBWS-Claims3.0.yaml#L1266) entity has some unnecessary properties, they are enums with only one option which are all required at [RB](https://rb.rb.is/display/B2BD/ClaimManagement.CreateClaim),  giving the consumer merely the illusion of choice.

The properties in question are calculationPeriod, calculationDayRule and defaultInterestException.

I suggest to remove these properties from IOBWS 3.0.

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-18 looked at the core system documentation that showed that the given properties only have a single available choice for enum, CalculationPeriod has [24-24], CalculationDayRule has [PaymentDay] and DefaultInterestException has [NoException]. The banks will take a notice of this, look into if this should be skipped in the creation but necessary in views or can be skipped altogether.

**Comment by Kristinn-Stefansson** [comment]
Marked as processed in line with agreement on TN-FMÞ-VH7-18 and PR
