### ISSUE TITLE
Claims - claimHistoryEvent

### ISSUE THREAD

**Issue by danielsveins** [stadlar/IST-FUT-FMTH#196]
In IOBWS 2.0 QueryClaimTransactions returns information about the claim after the transaction similar to what is defined in IOBWS 3.0 today for claimHistoryEvent.

The difference,. however, is that in the previous standard the information about the claim was of the type Claim. What the new standard returns (claimDetails) has more properties and comparable to ClaimInfo in the previous standard. There isn't technically an entity in IOBWS 3.0 that compares directly to Claim, the closest would be createClaimDetails (but the naming of it does not fit the context).

RB does not include these additional properties in [GetClaimEvents](https://rb.rb.is/display/B2BD/ClaimInfo.GetClaimEvents).

One possibility could be to rename createClaimDetails to claim (similar to the previous standard) and include that in claimHistoryEvent instead of claimDetails.

I wanted to open the conversation about this to see if there are any counterarguments for this being an issue.

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-18 discussed that there are disrepancies in how IOBWS 2.0 and consiquently RB returns information for transactions and history. We have to determine if we want to wait for the core system to be able to return these values and then amend the current specification. The suggestion is to propose having a closer alignment with the older approach. We will wait for more details in the issue.

**Comment by asgeirhall** [comment]
There is quite alot of properties that are diffrent from createClaimDetails and claimDetails.  Like all the calculated properties.

Since not everyone has access to the RB documentation it would be nice to know what properties are not there.

**Comment by danielsveins** [comment]
The following properties are a new addition to the response for the history of a claim (compared to IOBWS 2.0):

- claimStatus
- collectionState 
- closingDate
- secondaryCollectionClaimTemplateId
- categoryCode
- categoryDescription
- defaultChargeAmount
- defaultInterestAmount
- discountAmount
- noticeChargeAmount
- otherCostsAmount
- otherDefaultCostsAmount
- totalAmountDue
- isPartiallyPaid

I wonder whether these properties are only being added to the response because the "claim" part of it is _claimDetails_. Whereas in IOBWS 2.0 the "claim" part of the response was _Claim_, and not _ClaimInfo_. (ClaimInfo is to IOBWS 2.0 as claimDetails is to IOBWS 3.0)

Introducing these properties is maybe not an issue and we could wait for the core system to implement it. If, however, it turns out that they are being added on accident, then that's not a good basis for that "design decision".

If it's a deliberate decision to implement it this way then that's all good.

**Comment by kristinnstefansson** [comment]
This issue was addessed in the Claims 3.1 work done under workgroup VH-7. See the referenced comments and PR #198 as appropriate.
