### ISSUE TITLE
Claims - IsPostRefDate in the discount object

### ISSUE THREAD

**Issue by thebingi** [stadlar/IST-FUT-FMTH#201]
When creating a claim with a discount, there's an option to set isPostRefDate to either true or false within the discount object. This option is present in both claimDetails and createClaimDetails. However, according to the latest documentation from RB, the feature allowing for a discount after the reference date has been discontinued due to lack of use. Additionally, it seems counterintuitive to offer rewards for payments made after the due date.

Given this change, I suggest removing the isPostRefDate attribute from the discount object used in both claimDetails and createClaimDetails. Doing so will increase clarity, reduce potential confusion for those interacting with these objects.

**Comment by kristinnstefansson** [comment]
Meeting VH-7-19 discussed that it had no purpose as the functionality is not possible in the underlying core system. The PR will be accepted.

**Comment by kristinnstefansson** [comment]
This issue was addessed in the Claims 3.1 work done under workgroup VH-7. See the referenced comments and PR #198 as appropriate.
