### ISSUE TITLE
Discrepancy in CurrencyPaymentRate options for claims in foreign currency

### ISSUE THREAD

**Issue by thebingi** [stadlar/IST-FUT-FMTH#202]
In IOBWS 3.0, there are options to set differing CurrencyPaymentRate for Claims in foreign currency - DueDateRate and PaymentDateRate, a feature currently present in B2B.

Recently, DueDateRate was removed in RB, leaving only the option to input PaymentDateRate, else an error occurs. Therefore, I recommend removing this from the standard to prevent unnecessary confusion.

After inquiring about this with RB, this change was communicated to all banks and approved before it was removed

**Comment by kristinnstefansson** [comment]
Meeting VH-7-19 discussed that as the functionality is no longer possible in the underlying core system. This was aggreed and the PR will be accepted.

**Comment by kristinnstefansson** [comment]
This issue was addessed in the Claims 3.1 work done under workgroup VH-7. See the referenced comments and PR #198 as appropriate.
