### ISSUE TITLE
Claims - ClaimantAddress 

### ISSUE THREAD

**Issue by thebingi** [stadlar/IST-FUT-FMTH#203]
In the printing object, there are options to set both claimantAddress and payorAddress when creating and modifying claims. RB, however, only allows the setting of the payor's address, not the claimant's. Contrarily, there is an option to set the claimant's address on the Template, which seems more logical. It raises the question: why would one want to set different claimant addresses for claims being created? This inconsistency may lead to confusion and should be addressed.

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-20 discussed that this had probably been intended back in the day to anticipate the possibility that large corporates could vary the claimant address printed on slips. This is however not being used currently by the banks, so the meeting agreed on this being dropped from the specification.
