### ISSUE TITLE
claimantStatementReferenceType - description

### ISSUE THREAD

**Issue by asgeirhall** [stadlar/IST-FUT-FMTH#214]
The description of the claimantStatementReferenceType field is a bit wrong.  

Currently its "Indicates which value appears in the reference area on the creditor's account statement."

I think it should be "Indicates which value appears in the bill area on the creditor's account statement." (Not sure what new name for bill number in IOBS v3 accounts).

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-24 reviewed the status of this item, was accepted for merge

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-24 reviewed the status of this item, was accepted for merge
