### ISSUE TITLE
Type missing on enum type in depositAccountWithDetails

### ISSUE THREAD

**Issue by asgeirhall** [stadlar/IST-FUT-FMTH#215]
In type depositAccountWithDetails -> properties -> type

The enum is missing type: string like all the other enums have

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-22 reviewed and this seems to be an error, further investigation will be done and a Pull Request created to amend this if found to cause errors.

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-22 reviewed the status of this item, was accepted for merge
