### ISSUE TITLE
Fix missing references

### ISSUE THREAD

**Issue by asgeirhall** [stadlar/IST-FUT-FMTH#216]
Is it not needed to fix claims openapi document for missing ref items.  Its kinda strage to declare same type many times.

Example: 

- referenceDate is the same under defaultCharge and defaultInterest
- claimType
- collectionType
- claimantStatementExtendedReferenceType
- claimantStatementReferenceType

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-22 reviewed and this and there seem to be opportunities for improvements. Further investigations will be carried and one or more Pull Request created to amend this if found to cause problems.

**Comment by kristinnstefansson** [comment]
Meeting TN-FMÞ-VH7-22 reviewed the status of this item, still being worked on but not finished.

**Comment by kristinnstefansson** [comment]
TN-FMÞ-VH7-27 reviewed the status and on basis of the feedback this was merged.
