### ISSUE TITLE
Uppfæra töfluna hérna m.v. ákvarðanir síðustu viku?

### ISSUE THREAD

**Issue by hemmisnorra** [stadlar/IST-FUT-FMTH#26]
https://github.com/stadlar/IST-FUT-FMTH/wiki/Payment-Definitions-Payment-Initiation

**Comment by gudmundurjon** [comment]
Uppfært
-
https://github.com/stadlar/IST-FUT-FMTH/wiki/Payment-Definitions-Payment-Initiation
(Tók út listann)
- Samþykkt payment product er staðsett hérna
https://github.com/stadlar/IST-FUT-FMTH/wiki/Payment-Definitions

Kind regards
Guðmundur Jón Halldórsson
Co-Founder CEO | Crossing the line | www.ctl.is | +354 821 0885

ᐧ
