### ISSUE TITLE
Fjarlægja "Icelandic" úr nafngift greiðsluvara

### ISSUE THREAD

**Issue by hemmisnorra** [stadlar/IST-FUT-FMTH#27]
Niðurstaðan var held ég að í ljósi þess að um "Icelandic kafla" yrði að ræða innan Berlin Group að þá væri óþarfi að tiltaka "Icelandic" líka í nafngift sjálfra greiðsluvaranna:
https://github.com/stadlar/IST-FUT-FMTH/wiki/Payment-Product

Maður sér reyndar alveg kosti og galla í hvorutveggja en ég held samt að þetta sé rétt munað þannig að nafngiftin ætti að hverfa á þessu leveli og vera bara tiltekin í yfirflokkinum.

**Comment by gudmundurjon** [comment]
Þegar greiðsluvörur eru tilgreindar á síðunni https://github.com/stadlar/IST-FUT-FMTH/wiki/Payment-Product þá er notað fullt nafn, það nafn kemur síðan aftur fram í urli þjónustunnar. Dæmi:
Icelandic Domestic Credit Transfer -> Url: /v1/{payment-service}/icelandic-domestic-credit-transfer. 
Ég skal uppfæra til samræmis, verður eftir breytingu:
* Icelandic Domestic Credit Transfer (Account -> Account)
  * In url use /credit-transfer/
* Icelandic Domestic Claim Payment (Account -> Claim)
  * In url use /claim-payment/
* Icelandic Domestic Credit Card Deposit (Account -> Credit card)
  * In url use /credit-card-deposit/
