### ISSUE TITLE
Galli á skilgreiningu á remittanceInformationStructuredArray.  

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#40]
Þarf að skoða
a.	short - Text is visible to both payment sender and payment receiver: Þetta er ok.
b.	long - Text is visible to both payment sender and payment receiver and contains reference:  Þetta er ekki alveg ok.  Þetta eru raunverulega tvö jafnlöng svæði, annað er fyrir greiðandann og hitt er fyrir viðtakandann.  Ekki sama svæðið. 
i.	Einnig borgar sig ekki alveg strax að leyfa greiðanda að stjórna því hvað berst viðtakandanum þar sem þetta svæði er eingöngu hugsað fyir kennitölur í gömlum kerfum og flestum núverandi kerfum.
c.	Desc - Text is only visible to the sender and contains longer description. Þetta er ekki alveg ok. Svona svæði er ekki til í kjarnabankakerfinu þó það finnist locally hjá einhverjum banka.

**Comment by gudmundurjon** [comment]
Miðað við grunnkerfi RB er svarið rétt. Þessi svæði taka mið af því hvernig hópurinn vill að þetta sé í framtíðinni.

**Comment by siggauti** [comment]
**Nokkur dæmi um greiðslur og tilvísanir** |  
-- | --
  |  
**Uppgjör vegna   innheimtu skila** |  
PurposeCode | 03=Millifærsla
Structured.Reference   (35) | #uppgjörsnúmer
Structured.ReferenceIssuer   (35) | Alskil innheimta, uppgjör nr. #####
Skýring (140) | Nafn greiðanda kröfu
Tilvísun móttakanda | #kröfunúmer/#Málanúmer/#reikningur
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi | Kennitala greiðanda kröfu
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi | Kennitala eiganda kröfu
  |  
**Útlagt, kostnaður** |  
PurposeCode | BN=Endurgreiðsla
Structured.Reference   (35) | #beiðnanúmer
Structured.ReferenceIssuer   (35) |  
Skýring (140) | Útlagt - garðáhöld
Tilvísun móttakanda | #beiðnanúmer
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi |  
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi | Kennitala á kvittunum
  |  
**Greiðsla stjórnarlauna** |  
PurposeCode | 04=Laun
Structured.Reference   (35) | #mánuður
Structured.ReferenceIssuer   (35) |  
Skýring (140) | Stjórnarlaun maí
Tilvísun móttakanda | #mánuður
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi |  
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi | Kennitala stjórnarmanns
  |  
**Greiðsla reikninga** |  
PurposeCode | 37=Reikningur
Structured.Reference   (35) | #reikningsnúmer/#kröfunúmer
Structured.ReferenceIssuer   (35) | Nafn eiganda kröfu
Skýring (140) | Vinna vegna maí
Tilvísun móttakanda | #reikningsnúmer/#kröfunúmer
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi | Kennitala greiðanda kröfu
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi | Kennitala eiganda kröfu
  |  
**Millifærsla v/  framkvæmdasjóð** |  
PurposeCode | 03=Millifærsla,eigin reikninga
Structured.Reference   (35) | #mánuður
Structured.ReferenceIssuer   (35) |  
Skýring (140) | Fært í framkvæmdasjóð maí
Tilvísun móttakanda | #mánuður
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi |  
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi |  
  |  
**Hlutagreiðsla** |  
PurposeCode | HI=Innborgað
Structured.Reference   (35) | #reikningsnúmer/#kröfunúmer
Structured.ReferenceIssuer   (35) | Nafið á raun greiðanda
Skýring (140) | Skv. Samkomulagi nr. #
Tilvísun móttakanda | #samkomulagsnúmer
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi | Kennitala greiðanda kröfu
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi | Kennitala eiganda kröfu
  |  
**Greitt   til RSK vegna stofnun á nýrri kennitölu**
PurposeCode | 03=millifært
Structured.Reference   (35) | #beiðnanúmer
Structured.ReferenceIssuer   (35) | Nafnið á nýja félaginu
Skýring (140) | Stofna nýja kennitölu
Tilvísun móttakanda |  
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi |  
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi |  
  |  
**Innborgun   vegna vanskilainnheimtu**
PurposeCode | HI=Innborgað
Structured.Reference   (35) | #reikningsnúmer/#kröfunúmer/#málanúmer
Structured.ReferenceIssuer   (35) |  
Skýring (140) | Innborgun vegna xx kröfu
Tilvísun móttakanda | #reikningsnúmer/#kröfunúmer/#málanúmer
Greiðandi | Kt. Eiganda út-reiknings
Raun greiðandi | Kennitala greiðanda kröfu
Móttakandi | Kt. Eiganda inn-reiknings
Raun móttakandi | Kennitala eiganda kröfu
