### ISSUE TITLE
Gjaldmiðlagengi

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#43]
Sama og í sambankaskema í dag.
Gjaldmiðlategund, kaupgengi, sölugengi

Tegundir:
- Seðlabankagengi, tollagengi.

Viljum við skilgreina allar mögulegar tegundir, lámark tegunda eða enga tegund?

**Comment by hemmisnorra** [comment]
Til hliðsjónar er hér framsetning gjaldmiðlagengis í Landsbankaskemanu, sjá 5. kafla frá bls 47:
https://www.landsbankinn.is/Uploads/documents/FyrirtaekiFelog/landsbankinn_b2b_landsbankastadall.pdf

Og hér er sambanka útgáfan (2013) á framsetningu gjaldmiðlagengis:
https://www.landsbankinn.is/fyrirtaeki/rafraenar-lausnir/b2b/thjonustusidurb2b/sambankaskema/sambankaskema-2013/
