### ISSUE TITLE
Vísitölur

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#44]
Vísitala
- Nafn (Stutta skammstöfun)
- Dagsetning frá
- Dagsetning til

Stuðningur við að lágmarki:
- Útvals
..

**Comment by hemmisnorra** [comment]
Til hliðsjónar er hér framsetning vísitalna í Landsbankaskemanu, sjá 5. kafla frá bls 52:
https://www.landsbankinn.is/Uploads/documents/FyrirtaekiFelog/landsbankinn_b2b_landsbankastadall.pdf
