### ISSUE TITLE
Kort

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#45]
Fletta upp kortum bæði credit og debit.
Kortafærslur kortsins.

**Comment by hemmisnorra** [comment]
Til hliðsjónar er hér framsetning kreditkortayfirlita í Landsbankaskemanu, sjá 7. kafla frá bls 73: 
https://www.landsbankinn.is/Uploads/documents/FyrirtaekiFelog/landsbankinn_b2b_landsbankastadall.pdf

Arion banki hefur einnit gert svipað í eigin native skema. Er ekki með tæknihandbókarvefslóðina á takteinum.

**Comment by gudmundurjon** [comment]
Allir bankarnir ætla að senda á gudmundurjon@ctl.is sýnidæmi um kortayfirlit fyrir næsta fund.
