### ISSUE TITLE
Erlendar greiðslur

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#46]
1. Skilgreina greiðsluvöru fyrir erlendar greiðslur sem getur tekið við:
- JSON skilgreiningu á erlendri greiðsluskipun
- XML pain.001 skeiti.
2. Mappa svæði í pain.001 fyrir Íslenska banka.
3. Getað kallað eftir pain.002 sem er payment status report (Aðeins þegar pain.001 skeiti er sent inn)
4. Getað kallað eftir json payment status report (Aðeins þegar json skeiti hefur verið sent inn)

**Comment by hemmisnorra** [comment]
Til hliðsjónar er hér framsetning erlendra greiðslna í Landsbankaskemanu, sjá kafla 8.12, frá bls 147: 
https://www.landsbankinn.is/Uploads/documents/FyrirtaekiFelog/landsbankinn_b2b_landsbankastadall.pdf
