### ISSUE TITLE
Uppfæra til samræmis við Berlin-group 1.3.9

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#56]
Uppfæra yaml skjöl til samræmis við Berlin-group 1.3.9

**Comment by stadlar** [comment]
TN-FMÞ-VH7 ákvað að hinkra með þessa breytingu fram á vormisseri 2022 og taka þá útgáfu sem þá er nýjust ekki endilega 1.3.9.
