### ISSUE TITLE
Útgáfustýring innsendra rafrænna skjala

### ISSUE THREAD

**Issue by atliarion** [stadlar/IST-FUT-FMTH#58]
Við innsendingu á rafrænu skjali undir sama einkvæma ID ætti alltaf að verða til sem ný útgáfa. 
Móttakandi fengi alltaf nýjastu útgáfu sjálfgefið, en með fylgdi eigindi sem segði til að til um útgáfu og þar með hvort til væru eldri útgáfur. 
Það er þá útfærsluatriði hjá hverjum og einum þjónustuveitanda hvernig þeir birta notanda eldri útgáfur. Þá ætti jafnvel að vera hægt að leiðrétta skjöl sem notandi hefur þegar sótt en þá myndu þau birtast aftur sem ólesin.

**Comment by kristinnstefansson** [comment]
On meeting 24.11.2021 this was discussed as being additional functionality that will not be handled as VÞ6, when the requirements are known.

**Comment by kristinnstefansson** [comment]
@atliarion : Þetta fer á óskalista yfir breytingar á grunnkerfi.

**Comment by kristinnstefansson** [comment]
Needs to be discussed in the appropriate "Framtíðarhópur" in RB, as this affects product development.
