### ISSUE TITLE
Vísun í leyfi fyrir efni í kóðasafninu vantar

### ISSUE THREAD

**Issue by kristinnstefansson** [stadlar/IST-FUT-FMTH#59]
Eins og stendur er ekki vísað í Github leyfi á kóðasafninu, en það væri e.t.v. æskilegt til að gera það sem gegnsæjast. Við vorum með MIT þegar fyrri IOBWS útgáfur voru unnar (sjá t.d. afrit af [gamla CodePlex safninu frá 2010](https://github.com/kristinnstefansson/iceonlinebanking/blob/master/license.md)) en út frá venslum við Berlin Group þá er Creative Commons v4.0 það sem er mest viðeigandi og ég legg til að það verði stillingin. 

Það er væntanlega owner (@stadlar) sem verður að setja leyfið.

**Comment by stadlar** [comment]
TN-FMÞ-VH7-5 SEtja inn leyfi með textaskrá sem KS setur inn með readme inu.

**Comment by kristinnstefansson** [comment]
#60 innheldur leyfisskrá með öllum CC by 4 leyfistextanum.

**Comment by kristinnstefansson** [comment]
Búið að afgreiða PR 60, þessu atriði því.
