### ISSUE TITLE
Claims - Remove the ability to recreate claims

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#62]
**Suggestion**: Remove the ability to "recreate" claims which have been cancelled.

**Reasoning:** 

- From 1.1.2021 we have had a total of 11 claims resurrected - with 50% of them being resurrected by users in our online bank and the other half being resurrected by employees. And some of those 11 have since just been cancelled again.
- There is probably more to gain with the simplification of the system than the added inconvience for the claimants to create a new claim instead of the one being cancelled.
- We do not currently implement the ReCreateClaim/ReCreateClaims methods in IOBSv2 and we have never received any questions about it.

**Comment by asgeirh** [comment]
For collection companies re creating claims is very important.  Are you counting also claims that have been "altered" after being cancelled (aka recreated).

**Comment by gudnithor** [comment]
@asgeirh - I could be missing this in my query - do you have an example of a claim that you have recreated this way and can share the claim key with me so that I can trace this and see what happens? {my_github_username}@landsbankinn.is

**Comment by asgeirh** [comment]
@gudnithor I am sorry but in my current job I do not have many customers in Landsbankinn yet.

**Comment by gudnithor** [comment]
Totally fine - but I don't see the reason for having this as a special endpoint/route. Claims should have a status and we should just allow then to alter the status just like most of the other properties.

**Comment by asgeirh** [comment]
@gudnithor I would not be against it,  But Landsbankinn is the only bank that allows alter of cancelled claims.

**Comment by gudnithor** [comment]
I think it is important that this work is not only the interface but also some documentation/agreement about how everything should work. Making this standard is useless if we all implement it very differently :-)

**Comment by gudnithor** [comment]
**Suggestion from us:** 
This should be patch on the status of the claim - now this is a PUT with the whole claim in the body.

**Comment by gudnithor** [comment]
> I personally would prefer to recreate the claim in my exact status not the status before it was cancelled. 

So you want to create a new claim that has the same unique key as a previously created claim? If that is the issue the base system in RB should allow you to do that but that's not the intent of this operation.

**Comment by asgeirh** [comment]
Lets say that the claim was cancelled one month ago and we are recreating it.  Many factors could be changed.  And the window between alter and recreate could be big and allow the payor to pay the wrong amount.

Its important to remember that the claims system is doing most operations in batches that have to be processed by Caller, Bank and RB.  And once a claim is paid its not possible to rollback and fix the issue.
