### ISSUE TITLE
Claims - Get rid of the /claims/collection

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#63]
**Suggestion:** Remove the /claims/collection routes and MI companies instead use the same routes as everyone else with clear documentation about what they can and cannot do in them.

In the specs we now have /v1/claims with a lot of subresources and routes and then most of it is duplicated in the v1/claims/collection without any clear reason other than in IOBSv1 it was decided that the MI companies would use a different endpoint from the other companies.

In our systems the backend behind the _claims_ and _secondarycollection_ endpoints in IOBSv1/2 is exactly the same - there is just different access control behind. So instead of duplicating a lot of things, it will be properly documented what it is that MI companies/users can actually do.

**Comment by gudmundurjon** [comment]
Verkefni fyrir næsta fund, bankar skoða nánar.

**Comment by gudmundurjon** [comment]
Samþykkt á fundi 5.10.2021

**Comment by kristinnstefansson** [comment]
VH2 has been working on the authentication flows and scopes for IOBWS 3.0. After that review it would be our suggestion to keep (or split out) the secondary collection claim endpoints. Having the routes intermingled with the standard claimant functionality will make authentication/authorization somewhat convuluted and impact all the implementations with complex guard logic to make sure permissions leaks do not happen. One aspect of this is that all the secondary claimants are also primary claimants, but overall this makes the security logic more obscure.

**Comment by gudmundurjon** [comment]
Hópurinn samþykkir að hafa sama endapunkt fyrir bæði frum - og milliinnheimtu. Aðgangi að aðgerðum er stjórnað með réttinum.
