### ISSUE TITLE
Claims - Remove payorStatementExtendedReferenceType 

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#65]
**Suggestion:** Don't include payorStatementExtendedReferenceType in ClaimTemplates.

This comes from the RB services and we believe this is somewhat questionable property. It should not be up to the claimant to control what the reference is on the payor account statement - the payor controls this reference himself.

What do my collegues at the other banks say?

**Comment by gudmundurjon** [comment]
Allir samþykkir um að fjarlægja.
