### ISSUE TITLE
Claims - Remove customerNumberTemplate

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#66]
**Suggestion:** Don't include customerNumberTemplate in ClaimTemplates.

CustomerNumberTemplate works by putting a rule on the template that the customerNumber of all claims created in that template should follow. The claimant sets the customerNumber when creating a claim so he is not enforcing anyone else than himself.

This is also somewhat broken in IK at RB where there is a rule that all templates with the same category code (and the same claimant) must have the same customerNumberTemplate. So if you have a rule set and more than 1 template that share the same category code there is no way for anyone to change it as it fails the validation.

We in LB do not support this property and do not use it. 

What do my collegues at the other banks say - do you offer and use this?

**Comment by gudmundurjon** [comment]
Við viljum hafa þetta atriði inni.
