### ISSUE TITLE
Claims - Remove or make optional depositingAccount.errorText & depositingAccountWithDetails.errorText

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#68]
```
Error message for disposable invoice that was found during the last weekly debugging of claims formats.
```

I can see where this comes from (RB) but we do not currently use this functionality and probably never will, we have our own processes in place for dealing with the closure of accounts which are used by open claim templates.

+ Description of this property is flawed, "disposable invoice", "weekly debugging"?

**Comment by gudmundurjon** [comment]
Allir sammála um að þetta eigi ekki að vera inni.
