### ISSUE TITLE
Claims - Remove or make optional minimumCollectionAmount

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#69]
Same for this as many other properties - this exists at RB but we don't support it and never will.

**Comment by gudmundurjon** [comment]
minimumCollectionAmount is optional

**Comment by gummiolafs** [comment]
We are going to look into if this is used anywhere or can be safely removed.

**Comment by gudmundurjon** [comment]
Tökum svæðið "minimumCollectionAmount" út úr skjalinu.
