### ISSUE TITLE
Claims - Remove unpaidClaimCount

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#71]
```
        unpaidClaimCount:
          description: Fjöldi ógreiddra krafna skráð á kröfu sniðmát
          type: integer
```

Only property in the object that has an Icelandic description. 

**Suggestion:** Don't include this in the template - fetching this count can be very performance expensive and should belong in a special statistics route if needed. Another suggestion is to do a GET on claims/ which should also return some total count with the paging.

**Comment by gudmundurjon** [comment]
Taka út "unpaidClaimCount"

**Comment by gudmundurjon** [comment]
unpaidClaimCount has no meaningful information, removed.
