### ISSUE TITLE
Claims - Remove pattern/validation of kennitala and account ids

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#72]
As some of us are uncomfortably familiar with right now - things so concrete as kennitala can change. And since all the banks are going to use Sopra at RB there is only matter of time when the familiar xxxx-yy-zzzzzz account numbers will be replace with account numbers which will be something else.

**Suggestion:** Don't include any patterns, min/max values or restrictions where we are using kennitala and account numbers. They should just be strings.

**Comment by gudmundurjon** [comment]
N/A
