### ISSUE TITLE
Claims - PUT vs PATCH on a single claim

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#76]
PUT replaces the whole object which requires the users to send the whole object with all properties. PATCH instead just patches the properties which the user wants to change.

We suggest to replace the PUT method with a PATCH method on a single claim.

**Comment by gudmundurjon** [comment]
Samþykkt á fundi 5.10.2021

**Comment by gudmundurjon** [comment]
Valmöguleikar sem kosið verður um á næsta fundi er:
- PUT með fullu claimDetails sem endurspeglar RB objectið
- PATCH hlutabreyting

**Comment by gudmundurjon** [comment]
Arion banki, Íslandsbanki og Landsbankinn samþykkja að nota eingöngu PATCH fyrir breytingar.
