### ISSUE TITLE
The ASPSP may require the TPP to sign request messages

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#8]
The ASPSP may require the TPP to sign request messages. This requirement shall be 
stated in the ASPSP documentation.

**Comment by gudmundurjon** [comment]
Öll skilaboð (en. message) verða undirrituð.

**Comment by gislikonrad** [comment]
In chapter 4.2 in [the implemetation document](../blob/master/NextGenPSD2%20Access%20to%20Account%20Interoperability%20Framework/03.%20Implementation%20Guidelines%20V1.3.4_20190705.pdf), there is mention of the TPP-Signature-Certificate header.

In our opinion, at Landsbankinn, this is a vector for attack. If an attacker is able to inject himself between the client and the server, he will be able to replace the digest, the signature, and the certificate.

The signHTTP standard (draft-10 and above) has no mention of a Certificate header and relies only on the keyId in the signature header itself which the server uses to find the certificate in its own stores.
