### ISSUE TITLE
Claims - PUT /claims/{id}/recreate

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#81]
Split from issue #62 

/recreate is not a resource. This should be implemented by doing a PATCH on the status property on a single claim.

**Comment by gudnithor** [comment]
Need to discuss the newly created /v1/claims/RecreationBatch also.

**Comment by gudmundurjon** [comment]
Sjá fundargerð

**Comment by gudmundurjon** [comment]
Niðurstaðan er að "Recreate" er í raunni alter á kröfu.

**Comment by asgeirh** [comment]
> Niðurstaðan er að "Recreate" er í raunni alter á kröfu.

Recreate er samt aðgerð þótt hún geri það sama og alter.  Það er mjög óþægilegt að virkja kröfu sem einhver annar hefur fellt niður nema að maður vill gera það sérstaklega.  Er ekki hægt að bæta við property (Recreate claim if cancancelled þá)

**Comment by gudmundurjon** [comment]
Til að endurvekja kröfur væri kallað á PATCH með því að breita kröfunni úr "cancelled" í "unpaid". 

=> ? -> ?

Validation:
- Cancelled -> Unpaid; Þýðir "recreate"
- Unpaid -> Cancelled; Þýðir "cancelled"
- Annað ekki leyfilegt
