### ISSUE TITLE
Claims - PUT /claims/{id}/transfer

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#82]
This is a PUT without a body. PUT always has a body.

Suggest that we add a property to claimDetail which denotes if this claim will go into SecondaryCollection. So to send a claim to SecondaryCollection it's just a PATCH on that property.

**Comment by gudmundurjon** [comment]
Umræða um stöðubreytingar var eftirfarandi og verður kláruð á næsta fundi.

Claim state transfer
=> Primary -> Secondary 
=> Secondary -> Primary (SecondaryCollectionReturnClaim)

Íslandsbanki og Arion banki leggur til sér aðgerði.

Landsbankinn leggur til:
Notum attribute í gegnum alter til að færa kröfur frá frum í milli sem dæmi kröfuhafi sendir kröfur í milliinnheimtu.
Dæmi um stöðu breytingu:
- Alter claim {MarkForCollection -> Secondary collection}
- Alter claim {MarkForCollection -> Primary collection}

**Comment by snorrikarlsson** [comment]
Við sjáum fyrir okkur nokkra möguleika við að útfæra endapunkta fyrir stöðubreytingar. Báðar hugmyndirnar hafa það sameiginlegt að það er skýrt að verið er að breyta stöðu og setja af stað bisness feril. Til að koma til móts við óskir MI fyrirtækja þá geta þau sent í body hlutanum object sem uppfærir þau property sem þau mega breyta (þetta er fyrst og fremst vegna kostnaður við breytingar hjá RB).


- Tillaga 1
POST claims/{id}/collection-status 
{
	collectionStatus  = primary/secondary/legal
	Property1:
	Property2:
}

PUT claims/{id}/collection-status 
{
	Property1:
	Property2:	
}

- Tillaga 2
POST claims/{id}/primary-collection
{
	Property1:
	Property2:	
}
PUT claims/{id}/primary-collection
{
	Property1:
	Property2:
}

POST claims/{id}/secondary-collection
{
	Property1:
	Property2:
}
PUT claims/{id}/secondary-collection
{
	Property1:
	Property2:
}
POST claims/{id}/legal-collection
{
	Property1:
	Property2:	
}
PUT claims/{id}/legal-collection
{
	Property1:
	Property2:	
}

- Tillaga 3
Mögulega væri hægt að blanda þessum saman nota Post úr tillögu 2 og PUT úr tillögu 1

**Comment by gudmundurjon** [comment]
Til útskýringar á dæmi frá @snorrikarlsson:

Markmiðið er að setja í sér aðgerðir sem milliinnheimtuaðili má gera. 

1. Kröfuhafinn "1234567890" hefur stofnað kröfuna {Claimant:"1234567890", Account:"000166000001", DueDate: "2021-10-01"}
2. Kröfuhafinn vill senda kröfu í milliinnheimtu.
3. Kröfuhafi kallar á POST claims/{id}/secondary-collection (Ekkert body)
4. Milliinnheimtuaðili kallar á PUT claims/{id}/secondary-collection (Body), það er takmarkað sem milliinnheimtuaðili má breyta
5. Til að skila kröfu kallar milliinnheimtuaðili á POST claims/{id}/primary-collection (Ekki body)

**Comment by gudmundurjon** [comment]
Breyta attribute (Landbankinn) eða path aðgerð (Íslandsbanki). Arion banki er ekki kominn með niðurstöðu enþá.
Landsbankinn og Arion banki koma með dæmi. Umræðan verður á þessum þræði.

**Comment by gummiolafs** [comment]
Hérna er tillaga sem við byggjum á dæmum frá https://restfulapi.net/http-methods/

Leggjum til að innheimtustaða kröfu verði í collectionState property á kröfunni og hafi eftirfarandi stöður:

- "primary"
- "waitingForSecondary"
- "secondary"
- "legal" (ef við ætlum að bjóða á þetta yfir höfuð)

Þegar kröfuhafi vill senda kröfu í milliinnheimtu kallar hann í PATCH á kröfuna með eftirfarandi body. Þetta gæti líka gerst sjálfkrafa útaf dagareglu.
```
[
    { "op": "replace", "path": "status",  "value": "waitingForSecondary" },
]
```

Milliinnheimtufyrirtæki kallar reglulega í GET á kröfur og fær þá þessa kröfu þar inn í stöðunni waitingForSecondary. Kallar síðan í PATCH á kröfuna til að taka hana til sín í milliinnheimtu og bætir í leiðinni við öðrum vanskilakostnaði með eftirfarandi body:
```
[
    { "op": "replace", "path": "status",  "value": "secondary" },
    { "op": "replace", "path": "otherDefaultCosts",  "value": 15000 },
]
```

Í bönkum sem útfæra ekki waitingForSecondary er því milliskrefi sleppt og krafan sett beint í secondary. 

Með því að gera þetta svona er aldrei hætta á að öðru en því sem til stóð að breyta sé breytt. Einnig er hægt að gera fleiri en eina breytingu í hverju kalli og því ætti ekki að vera vandamál með mörg breytingagjöld.

**Comment by gudmundurjon** [comment]
Collection status:
* primary
* waitingForSecondary
* secondary
* legal

/v1/claims/{claimId}/transfer
body:
{
  "templateCode": "MI1",
  "otherDefaultCost": 999
}

/v1/claims/transfer
body:
[{
  "claimId": "",
  "templateCode": "MI1",
  "otherDefaultCost": 999
}]

Okkur vantar eitthvað betra nafn fyrir sub-resource-inn "transfer"
Það vantar dæmi.

**Comment by asgeirh** [comment]
Þetta virðist vera meira en transfer.   Þarf ekki bara að setja þetta í Alter líka sem optional property.  transferCollection: secondary

**Comment by gudmundurjon** [comment]
Nýtt dæmi

Collection status:
* primary
* waitingForSecondary
* secondary
* legal

Claim state transfer
=> Primary -> Secondary
=> Secondary -> Primary

POST /v1/claims/{claimId}/collection
body:
{
  "templateCode": "MI1", (Optional)
  "collection": "{collection}" (Required)
}

Setja magn í batch sem nýja týpu.
