### ISSUE TITLE
Claims - GET /claims/

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#84]
A lot of the query parameters have the description "Payor kennitala" - needs fixing.

date-type should be dateType - camelCase instead of kebab-case for consistency. DateType should have some default value so dateTo and dateFrom work if dateType is omitted.

claimant should be claimantId for consistency.

payor should be payorId for consistency.

state should be collectionState for a more descriptive name.

identifier does not work in this context, this needs to be templateId (similar key as we describe in issue #75) OR the identifier followed by the claimantId and branch id (the natural key for a template).

**Comment by gudmundurjon** [comment]
"Payor kennitala" -> laga skjölun, not rétt case for consistency.
