### ISSUE TITLE
Claims - Rework of batch operations

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#85]
POST /v1/claims  (batch)
POST /v1/claims/delete 
PUT /v1/claims

should be 

POST /v1/claimCreationBatches
POST /v1/claimAlterationBatches
POST /v1/claimDeletionBatches

We are creating a batch which will be run and we have three different types of batches with three different inputs. 

GET /v1/claims/info/{status-id}

should be

GET /v1/claimCreationBatches/{id}
GET /v1/claimAlterationBatches/{id}
GET /v1/claimDeletionBatches/{id}

PUT /v1/claims/recreate & PUT /v1/claims/transfer should get the same treatment as mentioned in issue #81 and #82 (put into the alteration).

**Comment by gudmundurjon** [comment]
1. Breyta POST /v1/claims (batch) -> POST /v1/claimCreationBatches
2. Breyta POST /v1/claims/delete -> POST /v1/claimCancellationBatches
3. Breyta PUT /v1/claims -> POST /v1/claimAlterationBatches
4. Bæta við GET /v1/claimCreationBatches/{id}
5. Bæta við GET /v1/claimAlterationBatches/{id}
6. Bæta við GET /v1/claimCancellationBatches/{id}
7. Fella út GET /v1/claims/info/{status-id}

**Comment by gudnithor** [comment]
/v1/claims/CreationBatch has the description "Gets a list of claims previously created by POST CreationBatch method" - we don't want to return a list of all the batches, we want to provide a way to retrieve a single batch by id.

**CreationBatch/CancellationBatch/AlterationBatch should be plural and should not be a subresource under /claims/.**

The contract is missing all these operations which are above in the issue:
GET /v1/claimCreationBatches/{id}
GET /v1/claimAlterationBatches/{id}
GET /v1/claimDeletionBatches/{id}
