### ISSUE TITLE
Claims - Document routes

### ISSUE THREAD

**Issue by gudnithor** [stadlar/IST-FUT-FMTH#86]
POST /v1/claims/{id}/documents

should be

POST /v1/claims/{id}/documentReference

as we are not adding the documents, we are just attaching a reference to a document stored elsewhere. 

DELETE /v1/claims/{id}/documentReference/{documentReferenceId}

documentReferenceId is a reference decided by the service provider

--

Don't we also need GET for a list of all documentReferences and single documentReference by id?

**Comment by gudmundurjon** [comment]
1. Endurnefna /v1/claims/{id}/documents -> /v1/claims/{id}/documentReferences
2. /v1/claims/{claim-id}/documents/{document-store-location}/{file-id} -> /v1/claims/{id}/documentReferences/{document-reference-id}
3. Bæta við GET /v1/claims/{claim-id}/documentReferences
4. Bæta við GET /v1/claims/{claim-id}/documentReferences/{document-reference-id}
