### ISSUE TITLE
Idem potency strategy

### ISSUE THREAD

**Issue by gudmundurjon** [stadlar/IST-FUT-FMTH#99]
Idem potency strategy:

X-Request-ID is required by every method and the answer to the request contains the same X-Request-ID. This has two reasons:
1. Request is paired with the Response by the same X-Request-ID. This is the same patterns as used by other services.
2. If the same X-Request-ID is used again then the previous answer is returned for GET, PUT, DELETE, HEAD, OPTIONS and TRACE

**Comment by kristinnstefansson** [comment]
@gudmundurjon : Add references to code changes and close issues.
